datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
  - name: loki
    type: loki
    url: http://loki:3100
  - name: tempo
    type: tempo
    url: http://tempo:3200
